### ISSUE TITLE
scala-native & libpcap article + code: update to latest scala-native

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#57]
https://www.scalawilliam.com/scala-native-libpcap/
Using 0.1.0 (https://github.com/ScalaWilliam/scala-native-libpcap/blob/master/project/p.sbt)
Latest: 0.3.1 (June 29, 2017)

Do whatever's necessary. Code may need to be updated, and make sure it works.
I'll pay $25 for this.

Add new section in article to show that there's been a change.

**Comment by Keshi** [comment]
Not sure what/if you want to say in your article, but I've opened a pull request that fixes your code to support 0.3.1.  https://github.com/ScalaWilliam/scala-native-libpcap/pull/2
I didn't make any code changes in any sections mentioned in your article.

**Comment by Keshi** [comment]
Does this work for the article? #58

**Comment by ScalaWilliam** [comment]
Made comments on your first PR.
