### ISSUE TITLE
$20: Migrate PasteBox (SVN @ SourceForge) to a Git repo

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#60]
I tried to do this myself using a standard set of instructions but didn't have any luck. It might not be straightforward but perhaps someone already has done this from SourceForge.

Here's the website for PasteBox: http://pastebox.sourceforge.net/

I want to extract a Git repo to back it up easily & put up on GitHub, for historical and nostalgic reasons.

As Git requires an e-mail address for each committer, set it to 'hello@scalawilliam.com', name 'William Narmontas'. Each commit must have a timestamp and the right set of changes associated with it.

Host it on GitHub, put finished URL here.

I'll pay $20 for this. Rules @ http://work.scalawilliam.com/rules/

ScalaWilliam Work item: http://work.scalawilliam.com/migrate-pastebox-svn-git/

**Comment by ScalaWilliam** [comment]
Would be great to know all the steps involved

**Comment by ThiefMaster** [comment]
Done. I requested to transfer that repo to you. Most likely GitHub sent you an email with a link to accept the repo transfer.

FYI, This was literally done by pasting your SVN url https://svn.code.sf.net/p/pastebox/code/ into https://github.com/new/import

**Comment by ScalaWilliam** [comment]
@ThiefMaster Thanks, it satisfies my requirement.
Please check your GitHub account e-mail for payment.
