### ISSUE TITLE
Migrate JMX article to here

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#61]
I would like to migrate my content to my own website in order to [own my data](https://indieweb.org/own_your_data).

Article is posted here: https://hackernoon.com/feature-switches-inheritance-and-agile-with-scala-jmx-on-the-jvm-140b4bf94d9f

I'd like it to be put in `/1609/feature-switches-agile-scala-jmx/` on the website here. This involves updating `build.sh` (means adding some rsync commands there), so you'll need to get familiar with that.

In the migration:
- Take source HTML and make into plain semantic HTML.
- Add [Microformats2](http://microformats.org/wiki/microformats-2) where it makes sense.
- You can use this as the outer template: https://www.scalawilliam.com/scala-native-libpcap/
- Migrate the Gist code blocks into `<pre><code>` tags.
- Migrate the images.
- Update index.php to refer to this link.

FYI I may ask for a few things that are not defined here, as I may have forgotten something important.

I'll pay $35 for this. Any questions, ask only here and not anywhere else. Rules: http://work.scalawilliam.com/rules/

This work is posted on http://work.scalawilliam.com/migrate-jmx-article/ & also https://git.work/

**Comment by brulzki** [comment]
Hi, I've submitted a pull request for this
https://github.com/ScalaWilliam/ScalaWilliam.com/pull/62

**Comment by ScalaWilliam** [comment]
This was solved.
