### ISSUE TITLE
Add representative h-card to the homepage

### ISSUE THREAD

**Issue by Zegnat** [ScalaWilliam/ScalaWilliam.com#63]
As an IndieWeb term, the [homepage](https://indieweb.org/homepage):

> <i>[…]</i> represents you on the web, typically at the top of your domain, and shows your name and an iconic representation, often marked up with h-card.

It shouldn’t be hard to turn the top of the current homepage into an h-card. Most information that would be seen as important is already there like name, email, links to silos (already with `rel="me"`!), etc.

Making sure to match the algorithm for [a representative h-card](http://microformats.org/wiki/representative-hcard) will allow more h-cards to be added to the page (e.g. one for Apt Elements Ltd.) in the future without parsers getting confused which card is yours.

**Comment by ScalaWilliam** [comment]
This is trivial from what I understand. I'd pay $5 for it.
