### ISSUE TITLE
Add an h-feed of articles

### ISSUE THREAD

**Issue by Zegnat** [ScalaWilliam/ScalaWilliam.com#64]
An [h-feed](http://microformats.org/wiki/h-feed) is a stream of entries embedded straight into the HTML of a page, that may be subscribed to by readers (or converted to other formats like RSS and Atom).

The current list of articles could make for a fine h-feed. It is not necessary to move all the articles to be self-hosted first. Every list item would be an [h-entry](http://microformats.org/wiki/h-entry), and links and names are already there. I would personally add a published date behind it but otherwise no changes to content are necessary to implement the extra markup.

An example h-feed of links to external articles would be [IndieNews](https://news.indieweb.org/en).

**Comment by ScalaWilliam** [comment]
This is great. I'll pay $10 for doing this work. While it's fairly trivial, you have to find the dates from each article and then add them to the page.
When adding them, `* <title>, <date>` is enough.

As I wish everything to be logged, can you create a PR in https://github.com/ScalaWilliam/Work/ posts for this issue? $5 for that PR.

$10 if you choose to complete this issue. If you feel that's too little just say so.

**Comment by Zegnat** [comment]
Per [the rules](http://work.scalawilliam.com/rules/): **“I’m taking on this”**.

**Question:** do you want https://www.scalawilliam.com/ to **be** the feed, as described on [the IndieWeb.org feed page](http://indieweb.org/feed)? Or would you prefer having just that one block on the homepage to be the feed?

The latter could follow [the discussed partial feed format](http://indieweb.org/h-feed#partial_feeds) and would allow you to upgrade other sections to partial feeds as well, but may come with less implementation amongst reading applications. (Specifically reading applications. The microformats parsers should all work with it just fine and people could easily write consumers.)

**Comment by Zegnat** [comment]
For a partial feed I would propose [this change](https://github.com/Zegnat/ScalaWilliam.com/commit/fe1af8c32f57f88b89761836d4b1dca3c2315792). The parsed output can be seen [on this temporary test page](https://php.microformats.io/?id=20170729140155133).

**Comment by ScalaWilliam** [comment]
Yes, partial feed is what I want.

**Comment by ScalaWilliam** [comment]
Note though that "Scala Nashorn Interaction, 29 Dec, 2016" could be better read as "Scala Nashorn Interaction, December 2016" (as per rest of the site) as I don't need precise dates for these things.

**Comment by Zegnat** [comment]
@ScalaWilliam if you could add that as review comments on #68 I am happy to update the times wherever you see fit.

**Comment by ScalaWilliam** [comment]
Thanks.
