### ISSUE TITLE
Migrate Scala Android opportunity article

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#65]
It's on the homepage as "Why Scala didn't miss the Android opportunity" 

Similar requirements to this completed issue: https://github.com/ScalaWilliam/ScalaWilliam.com/issues/61

Look at [this pull request comments](https://github.com/ScalaWilliam/ScalaWilliam.com/pull/62) for further guidance.

Please post here **before** starting the work, so that somebody else doesn't take on it.
This one is $15 as there's a precedent of work already and it doesn't contain any code blocks or images.

**Comment by brulzki** [comment]
While I'm in the groove after the last medium migration, I'm taking this on

**Comment by brulzki** [comment]
What year was that article published? It only has a date of "May 18"

**Comment by ScalaWilliam** [comment]
![screen shot 2017-07-29 at 22 17 25](https://user-images.githubusercontent.com/2464813/28745465-b940e9cc-74ab-11e7-9b39-a668d973abaa.png)
