### ISSUE TITLE
Migrate article: How I deal with greenfield technical debt

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#70]
Part of #55. Reference PRs and Issues on how to repeat this, basically: https://github.com/ScalaWilliam/ScalaWilliam.com/issues/61 https://github.com/ScalaWilliam/ScalaWilliam.com/issues/65 https://github.com/ScalaWilliam/ScalaWilliam.com/pull/67 https://github.com/ScalaWilliam/ScalaWilliam.com/pull/62

I'll pay $20 for this. It's not small, but it's not complex either, and there already are examples. 
http://work.scalawilliam.com/migrate-greenfield-article/

Make sure to post "**I'm taking on this**" before starting to lock the piece of work to yourself.

**Comment by Zegnat** [comment]
As per [the rules](http://work.scalawilliam.com/rules/):  “I’m taking on this”.
