### ISSUE TITLE
Migrate article: Limit degrees of freedom in development

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#71]
Part of #55. Reference PRs and Issues on how to repeat this, basically: https://github.com/ScalaWilliam/ScalaWilliam.com/issues/61 https://github.com/ScalaWilliam/ScalaWilliam.com/issues/65 https://github.com/ScalaWilliam/ScalaWilliam.com/pull/67 https://github.com/ScalaWilliam/ScalaWilliam.com/pull/62

I'll pay $15 for this. It's quite small and has two images.

Make sure to post "**I'm taking on this**" before starting to lock the piece of work to yourself. It's posted on http://work.scalawilliam.com/migrate-degrees-freedom-article/

**Comment by Zegnat** [comment]
As per [the rules](http://work.scalawilliam.com/rules/):  “I’m taking on this”.
