### ISSUE TITLE
Migrate dev.to article to this site: Certifications I'm considering, as an experienced software engineer

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#72]
Title: Certifications I'm considering, as an experienced software engineer

Part of #55. Reference PRs and Issues on how to repeat this, basically: https://github.com/ScalaWilliam/ScalaWilliam.com/issues/61 https://github.com/ScalaWilliam/ScalaWilliam.com/issues/65 https://github.com/ScalaWilliam/ScalaWilliam.com/pull/67 https://github.com/ScalaWilliam/ScalaWilliam.com/pull/62

I'll pay $15 for this. Much simpler than Medium ones. It's posted on: http://work.scalawilliam.com/migrate-certifications-article/

Make sure to post "**I'm taking on this**" before starting to lock the piece of work to yourself.
Rules: http://work.scalawilliam.com/rules/

**Comment by Zegnat** [comment]
As per [the rules](http://work.scalawilliam.com/rules/):  “I’m taking on this”.

I have the dev environment set-up anyway.
