### ISSUE TITLE
Migrate: Unit testing is simple, May 2017

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#77]
Part of #55. Use #72, #70, #71, #65 as inspiration.

#61 is most relevant inspiration. I want microformats where possible as well.

Also I'll pay extra $5 if you can propose well how to migrate some of the comments as well as a separate issue. They are quite good but I wouldn't know how to represent them. Post an issue for this.

For this I'll pay $15. For proper syntax highlighting for all languages I'll add extra $5, as the existing examples don't come with anything other than Scala highlighting and that may be extra work.

I intend to update this article and keep it up to date. Also it should be hosted in `/unit-testing-is-simple/` because it's going to be timeless.

As always, rules are here: http://work.scalawilliam.com/rules/

To lock the issue to yourself, post here as per the rules.

Issue is posted here as well: http://work.scalawilliam.com/migrate-unit-testing-article/

**Comment by Zegnat** [comment]
As per [the rules](http://work.scalawilliam.com/rules/):  “I’m taking on this”.
