### ISSUE TITLE
Migrate & include article:  Web standards for content syndication

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#88]
Canonical path will have to be `/web-standards-for-content-syndication/`.

* Migrate from dev.to to here - similar to stuff done in #55
* Add link from index.php to it.
* You may include comments if you wish, but I will not pay extra for it.

Here it is:
https://dev.to/scalawilliam/web-standards-for-content-syndication

I'll pay $10 for it.

**Comment by Zegnat** [comment]
Per [the rules](http://work.scalawilliam.com/rules/): I’m taking on this. Expect a PR later today.

**Comment by ScalaWilliam** [comment]
Closed by #89. Thanks very much. Payment incoming now.
