### ISSUE TITLE
$20-$28: Create Dockerfile that builds everything with `make`

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ScalaWilliam.com#98]
So that:
- I can build the site from within a Docker image, and thus build previews independently - ie #97
- Travis build would be lighter and less Travis-specific

Contains make, php, composer.

Save the Docker image as `build/Dockerfile`. The way I see this working is by:

```
$ git clone https://github.com/ScalaWilliam/ScalaWilliam.com.git sw
$ cd sw
$ docker build -t sw-build build/Dockerfile
$ docker run -v $PWD:/sw -it sw-build bash -c 'cd /sw/ && composer install && make'
$ echo $?
0
```

I'll pay US$20 for this as specified on [ScalaWilliam Work item: Dockerfile for website](http://work.scalawilliam.com/dockerfile-website/).
To take on this, comment "**I agree to the [ScalaWilliam Work rules](http://work.scalawilliam.com/rules/) and am taking on this task**".

**$8 bonus** if completed correctly before Saturday 23:59:59 UTC!
Please correct me if there're any mistakes.

**Comment by philicious** [comment]
hi @ScalaWilliam .. came here via Twitter .. 

```
docker run --rm --interactive --tty --volume $PWD:/app composer install && make
```
using https://hub.docker.com/r/library/composer/ .. so no need to roll your own Dockerfile. Unless you need customizations to compose et.al.

**Comment by ScalaWilliam** [comment]
Not quite, that doesn't work, `make` must run inside the container.

**Comment by philicious** [comment]
@ScalaWilliam ah ye you are right. I was a bit quick on this. see my PR
